name: 'SBT Test Sharding'
description: 'Automatically shard Scala tests for parallel execution in CI'
author: 'juanri0s'
inputs:
  max-shards:
    description: 'Maximum number of shards to split tests into'
    required: true
  shard-number:
    description: 'Current shard number (1-indexed). Should match matrix.shard when using matrix strategy. Defaults to 1.'
    required: false
    default: '1'
  algorithm:
    description: 'Sharding algorithm to use (supports: "round-robin", "complexity")'
    required: false
    default: 'round-robin'
  test-pattern:
    description: 'Pattern to match test files (default: **/*Test.scala,**/*Spec.scala,**/Test*.scala,**/Spec*.scala)'
    required: false
    default: '**/*Test.scala,**/*Spec.scala,**/Test*.scala,**/Spec*.scala'
  project-path:
    description: 'Optional project directory path to filter test files. If provided, only test files within this directory will be included.'
    required: false
outputs:
  total-shards:
    description: 'Total number of shards created'
  test-files:
    description: 'Comma-separated list of test files to run in this shard'
  test-commands:
    description: 'SBT commands to run tests for this shard'
  shard-matrix:
    description: 'JSON array of shard numbers for use in GitHub Actions matrix (e.g., [1,2,3])'
runs:
  using: 'node24'
  main: 'dist/index.js'
