name: 'SBT Test Sharding'
description: 'Automatically shard Scala tests for parallel execution in CI'
author: 'juanri0s'
inputs:
  max-shards:
    description: 'Maximum number of shards to split tests into (ignored if auto-shard-matrix is true)'
    required: false
  auto-shard-matrix:
    description: 'Automatically determine the number of shards based on test file count and output only the shard matrix (no file distribution)'
    required: false
    default: 'false'
  algorithm:
    description: 'Sharding algorithm to use (supports: "round-robin", "complexity"). Not used when auto-shard-matrix is true.'
    required: false
    default: 'round-robin'
  test-pattern:
    description: 'Pattern to match test files (default: **/*Test.scala,**/*Spec.scala,**/Test*.scala,**/Spec*.scala)'
    required: false
    default: '**/*Test.scala,**/*Spec.scala,**/Test*.scala,**/Spec*.scala'
outputs:
  total-shards:
    description: 'Total number of shards created'
  test-files:
    description: 'Comma-separated list of test files to run in this shard'
  test-commands:
    description: 'SBT commands to run tests for this shard'
  shard-matrix:
    description: 'JSON array of shard numbers for use in GitHub Actions matrix (e.g., [1,2,3])'
runs:
  using: 'node24'
  main: 'dist/index.js'
