name: "SBT Test Sharding"
description: "Automatically shard Scala tests for parallel execution in CI"
author: "juanri0s"
inputs:
  max-shards:
    description: "Maximum number of shards to split tests into"
    required: true
  algorithm:
    description: 'Sharding algorithm to use (currently supports: "test-file-count")'
    required: false
    default: "test-file-count"
  test-pattern:
    description: "Pattern to match test files (default: **/*Test.scala,**/*Spec.scala)"
    required: false
    default: "**/*Test.scala,**/*Spec.scala"
  shard-number:
    description: "Current shard number (1-indexed). If not provided, will use GITHUB_SHARD env var or default to 1"
    required: false
outputs:
  shard-number:
    description: "The current shard number (1-indexed)"
  total-shards:
    description: "Total number of shards created"
  test-files:
    description: "Comma-separated list of test files to run in this shard"
  test-commands:
    description: "SBT commands to run tests for this shard"
runs:
  using: "node24"
  main: "dist/index.js"
